//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangResources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LangResources.Resources.lang uk", typeof(lang_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відміна.
        /// </summary>
        public static string CancelBttn {
            get {
                return ResourceManager.GetString("CancelBttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити локалізацію.
        /// </summary>
        public static string ChangeLangBttn {
            get {
                return ResourceManager.GetString("ChangeLangBttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я:.
        /// </summary>
        public static string NameTxtBlck {
            get {
                return ResourceManager.GetString("NameTxtBlck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string OkBttn {
            get {
                return ResourceManager.GetString("OkBttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон:.
        /// </summary>
        public static string PhoneTxtBlck {
            get {
                return ResourceManager.GetString("PhoneTxtBlck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище:.
        /// </summary>
        public static string SurnameTxtBlck {
            get {
                return ResourceManager.GetString("SurnameTxtBlck", resourceCulture);
            }
        }
    }
}
